spring:
  application:
    name: questionservice
  datasource:
    url: jdbc:postgresql://localhost:5432/quizzapp  # PostgreSQL connection URL other database questionservice
    username: postgres                             # Your PostgreSQL username
    password: root                             # Your PostgreSQL password
    driver-class-name: org.postgresql.Driver

    # Show SQL in logs for debugging
  jpa:
    hibernate:
      ddl-auto: update   # creates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect